FROM registry.cn-hangzhou.aliyuncs.com/library/node:20-alpine AS builder

WORKDIR /app/web

RUN npm config set registry https://registry.npmmirror.com

COPY web/package*.json ./
RUN npm install

COPY web/ ./
RUN npm run build

FROM registry.cn-hangzhou.aliyuncs.com/library/nginx:alpine

COPY deploy/nginx-docker.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
